const connectDB = require("./dbscheme");
const Scheme = require("../models/Scheme");

const schemes = [
  {
    schemeName: "National Agriculture Market (eNAM)",
    description: "A platform for online trading of agricultural commodities.",
    state: "Rajasthan",
    cropType: "Cotton",
    incomeLevel: "Low",
    eligibility: "Farmers and traders across the country.",
    amount: 5000,
    applicationDeadline: new Date("2024-09-30T00:00:00Z"),
    contact: "+91 9123456789",
    website: "https://www.enam.gov.in",
  },
  {
    schemeName: "Kisan Credit Card Scheme",
    description: "A credit card to provide farmers with easy access to short-term loans.",
    state: "Uttar Pradesh",
    cropType: "Sugarcane",
    incomeLevel: "Medium",
    eligibility: "Farmers who need credit facilities for agricultural activities.",
    amount: 25000,
    applicationDeadline: new Date("2024-12-15T00:00:00Z"),
    contact: "+91 9134567890",
    website: "https://www.pmkisan.gov.in/Kisan_Credit_Card.aspx",
  },
  {
    schemeName: "Soil Health Management (SHM) Scheme",
    description: "A scheme to enhance soil health and productivity by providing soil health cards.",
    state: "Punjab",
    cropType: "Maize",
    incomeLevel: "Low",
    eligibility: "Farmers in rural areas with poor soil health.",
    amount: 1500,
    applicationDeadline: new Date("2024-10-31T00:00:00Z"),
    contact: "+91 9145678901",
    website: "https://soilhealth.dac.gov.in",
  },
  {
    schemeName: "Pradhan Mantri Krishi Sinchayee Yojana",
    description: "A scheme to promote irrigation systems in farms and ensure water use efficiency.",
    state: "Gujarat",
    cropType: "Rice",
    incomeLevel: "Medium",
    eligibility: "Farmers who need irrigation systems for water management.",
    amount: 12000,
    applicationDeadline: new Date("2024-11-25T00:00:00Z"),
    contact: "+91 9156789012",
    website: "https://pmksy.gov.in",
  },
  {
    schemeName: "Rashtriya Krishi Vikas Yojana",
    description: "A scheme aimed at increasing agricultural production and improving rural infrastructure.",
    state: "Madhya Pradesh",
    cropType: "Wheat",
    incomeLevel: "High",
    eligibility: "Farmers with large-scale production setups.",
    amount: 30000,
    applicationDeadline: new Date("2024-12-20T00:00:00Z"),
    contact: "+91 9167890123",
    website: "https://rkvy.nic.in",
  },
  {
    schemeName: "Atal Bhujal Yojana",
    description: "A scheme for sustainable groundwater management and water conservation.",
    state: "Haryana",
    cropType: "Cotton",
    incomeLevel: "Low",
    eligibility: "Farmers in water-scarce regions.",
    amount: 10000,
    applicationDeadline: new Date("2024-09-15T00:00:00Z"),
    contact: "+91 9178901234",
    website: "https://ataljal.mowr.gov.in",
  },
  {
    schemeName: "Paramparagat Krishi Vikas Yojana",
    description: "A scheme to promote organic farming through training and financial assistance.",
    state: "Kerala",
    cropType: "Spices",
    incomeLevel: "Medium",
    eligibility: "Farmers interested in converting to organic farming practices.",
    amount: 25000,
    applicationDeadline: new Date("2024-10-10T00:00:00Z"),
    contact: "+91 9189012345",
    website: "https://pky.gov.in",
  },
  {
    schemeName: "Mission for Integrated Development of Horticulture",
    description: "A scheme to promote the development of horticulture in the country.",
    state: "Uttarakhand",
    cropType: "Apples",
    incomeLevel: "Medium",
    eligibility: "Farmers engaged in horticulture-based farming.",
    amount: 18000,
    applicationDeadline: new Date("2024-12-05T00:00:00Z"),
    contact: "+91 9190123456",
    website: "https://midh.gov.in",
  },
  {
    schemeName: "National Mission on Agricultural Extension and Technology",
    description: "A scheme to support agricultural extension activities and promote new technologies.",
    state: "Andhra Pradesh",
    cropType: "Pulses",
    incomeLevel: "Low",
    eligibility: "Farmers in need of technology-driven farming solutions.",
    amount: 5000,
    applicationDeadline: new Date("2024-11-30T00:00:00Z"),
    contact: "+91 9201234567",
    website: "https://agricoop.nic.in/en/technology",
  },
  {
    schemeName: "Fisheries and Aquaculture Infrastructure Development Fund",
    description: "A scheme to improve fisheries infrastructure and provide financial assistance for fisheries development.",
    state: "West Bengal",
    cropType: "Fish",
    incomeLevel: "High",
    eligibility: "Fisheries and aquaculture farmers looking to improve infrastructure.",
    amount: 40000,
    applicationDeadline: new Date("2024-10-25T00:00:00Z"),
    contact: "+91 9212345678",
    website: "https://dof.gov.in/faidf",
  },
  {
    schemeName: "Kisan Suryoday Yojana",
    description: "A scheme for farmers to get reliable electricity for irrigation purposes.",
    state: "Maharashtra",
    cropType: "Sugarcane",
    incomeLevel: "Low",
    eligibility: "Farmers requiring consistent electricity supply for irrigation.",
    amount: 6000,
    applicationDeadline: new Date("2024-11-15T00:00:00Z"),
    contact: "+91 9223456789",
    website: "https://mahadiscom.in/kisan-suryoday-yojana",
  },
  {
    schemeName: "PM Kisan Yojana",
    description: "A scheme for financial assistance to farmers.",
    state: "Karnataka",
    cropType: "Rice",
    incomeLevel: "Low",
    eligibility: "Farmers with less than 2 hectares of land",
    amount: 6000,
    applicationDeadline: new Date("2024-12-31T00:00:00Z"),
    contact: "+91 9876543210",
    website: "https://pmkisan.gov.in",
  },
  {
    schemeName: "Pradhan Mantri Fasal Bima Yojana",
    description: "A crop insurance scheme for farmers.",
    state: "Maharashtra",
    cropType: "Wheat",
    incomeLevel: "Medium",
    eligibility: "Farmers growing wheat for commercial purposes",
    amount: 10000,
    applicationDeadline: new Date("2024-11-30T00:00:00Z"),
    contact: "+91 9876543211",
    website: "https://pmfby.gov.in",
  },
  {
    schemeName: "Fertilizer Subsidy Scheme",
    description: "A subsidy scheme for farmers to reduce the cost of fertilizers.",
    state: "Bihar",
    cropType: "Paddy",
    incomeLevel: "Low",
    eligibility: "Farmers who purchase fertilizers for crop production.",
    amount: 3000,
    applicationDeadline: new Date("2024-11-15T00:00:00Z"),
    contact: "+91 9209876543",
    website: "https://fertilizersubsidy.gov.in",
  },
  {
    schemeName: "Rural Agricultural Work Experience (RAWE)",
    description: "An initiative for providing agricultural work experience to students.",
    state: "Maharashtra",
    cropType: "Groundnut",
    incomeLevel: "Medium",
    eligibility: "Agricultural students seeking practical exposure.",
    amount: 1500,
    applicationDeadline: new Date("2024-12-01T00:00:00Z"),
    contact: "+91 9134567895",
    website: "https://rawe.gov.in",
  },
  {
    schemeName: "National Bee Board Scheme",
    description: "A scheme to promote beekeeping as a sustainable livelihood option.",
    state: "Uttarakhand",
    cropType: "Honey",
    incomeLevel: "Medium",
    eligibility: "Farmers and individuals interested in beekeeping.",
    amount: 12000,
    applicationDeadline: new Date("2024-12-10T00:00:00Z"),
    contact: "+91 9198765432",
    website: "https://nbb.gov.in",
  },
  {
    schemeName: "Bamboo Development Scheme",
    description: "A scheme for promoting bamboo cultivation and processing.",
    state: "Nagaland",
    cropType: "Bamboo",
    incomeLevel: "Medium",
    eligibility: "Farmers interested in bamboo cultivation.",
    amount: 20000,
    applicationDeadline: new Date("2024-11-30T00:00:00Z"),
    contact: "+91 9299876543",
    website: "https://bamboo.gov.in",
  },
  {
    schemeName: "Solar Pumping Scheme",
    description: "A subsidy for farmers to install solar pumps for irrigation.",
    state: "Madhya Pradesh",
    cropType: "Cotton",
    incomeLevel: "Low",
    eligibility: "Farmers with limited access to electricity.",
    amount: 50000,
    applicationDeadline: new Date("2024-11-25T00:00:00Z"),
    contact: "+91 9301234567",
    website: "https://solarpumpscheme.gov.in",
  },
  {
    schemeName: "Pradhan Mantri Annadata Aay SanraksHan Abhiyan",
    description: "A scheme to ensure a fair minimum price for farm produce.",
    state: "Uttar Pradesh",
    cropType: "Sugarcane",
    incomeLevel: "Medium",
    eligibility: "Farmers engaged in sugarcane farming.",
    amount: 10000,
    applicationDeadline: new Date("2024-12-12T00:00:00Z"),
    contact: "+91 9112345678",
    website: "https://pmkisan.gov.in",
  },
  {
    schemeName: "Swachh Bharat Mission (Gramin)",
    description:
      "A mission to improve sanitation and promote cleanliness in rural areas.",
    state: "Tamil Nadu",
    cropType: "Vegetables",
    incomeLevel: "Low",
    eligibility: "Rural communities and farmers focused on cleanliness.",
    amount: 3000,
    applicationDeadline: new Date("2024-11-20T00:00:00Z"),
    contact: "+91 9178901234",
    website: "https://swachhbharatmission.gov.in",
  },
  {
    schemeName:
      "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
    description:
      "A rural employment guarantee scheme to provide job opportunities.",
    state: "West Bengal",
    cropType: "Rice",
    incomeLevel: "Low",
    eligibility: "Rural unemployed individuals looking for work.",
    amount: 2000,
    applicationDeadline: new Date("2024-12-01T00:00:00Z"),
    contact: "+91 9283456789",
    website: "https://mgnrega.nic.in",
  },
  {
    schemeName: "Pradhan Mantri Kisan Samman Nidhi Yojana (PM-KISAN)",
    description:
      "A scheme to provide financial assistance to small and marginal farmers.",
    state: "Kerala",
    cropType: "Coconut",
    incomeLevel: "Low",
    eligibility: "Small farmers owning less than 2 hectares of land.",
    amount: 6000,
    applicationDeadline: new Date("2024-12-31T00:00:00Z"),
    contact: "+91 9887654321",
    website: "https://pmkisan.gov.in",
  },
  {
    schemeName: "Mission Organic Value Chain Development in North East Region",
    description:
      "A scheme to promote organic farming in the North East region.",
    state: "Assam",
    cropType: "Organic Tea",
    incomeLevel: "Medium",
    eligibility: "Farmers interested in organic tea farming.",
    amount: 25000,
    applicationDeadline: new Date("2024-11-30T00:00:00Z"),
    contact: "+91 9223456781",
    website: "https://movcdner.gov.in",
  },
  {
    schemeName: "National Mission for Sustainable Agriculture",
    description:
      "A scheme aimed at promoting sustainable agricultural practices.",
    state: "Odisha",
    cropType: "Groundnut",
    incomeLevel: "Low",
    eligibility: "Farmers engaged in groundnut cultivation.",
    amount: 5000,
    applicationDeadline: new Date("2024-11-05T00:00:00Z"),
    contact: "+91 9345678901",
    website: "https://nmsa.nic.in",
  },
  {
    schemeName: "Integrated Watershed Management Programme (IWMP)",
    description:
      "A program to restore watersheds for better water conservation.",
    state: "Rajasthan",
    cropType: "Pulses",
    incomeLevel: "Low",
    eligibility: "Farmers working in watershed areas.",
    amount: 12000,
    applicationDeadline: new Date("2024-12-10T00:00:00Z"),
    contact: "+91 9287654321",
    website: "https://iwmp.gov.in",
  },
  {
    schemeName: "Horticulture Mission for North East and Himalayan States",
    description:
      "A scheme for the development of horticulture in the North East and Himalayan regions.",
    state: "Sikkim",
    cropType: "Oranges",
    incomeLevel: "Medium",
    eligibility: "Farmers in North East and Himalayan regions.",
    amount: 15000,
    applicationDeadline: new Date("2024-12-15T00:00:00Z"),
    contact: "+91 9198765433",
    website: "https://midh.gov.in",
  },
  {
    schemeName: "National Livestock Mission",
    description: "A scheme to support the development of livestock farming.",
    state: "Haryana",
    cropType: "Dairy",
    incomeLevel: "Medium",
    eligibility: "Farmers engaged in dairy farming.",
    amount: 20000,
    applicationDeadline: new Date("2024-11-22T00:00:00Z"),
    contact: "+91 9345678905",
    website: "https://dahd.nic.in",
  },
];

const insertSchemes = async () => {
  await connectDB(); // Connect to MongoDB Atlas
  try {
    const result = await Scheme.insertMany(schemes); // Insert data
    console.log("Data inserted:", result);
  } catch (err) {
    console.error("Error inserting data:", err.message);
  }
};

insertSchemes(); // Execute the insert function
